=== Wirecloud/ogc-nomenclator-geowidget/js/service-config/service_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="serviceConfig">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="request">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="url" type="xs:anyURI"/>
							<xs:element name="namespace" type="xs:string"/>
							<xs:element name="typename" type="xs:string"/>
							<xs:element name="filter" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="results">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="locationInfo">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="attribute" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="location">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="attribute" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="srs">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="attribute" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="displayInfo" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:anyURI">
											<xs:attribute name="headChar" use="optional">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:length value="1"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="trailChar" use="optional">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:length value="1"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="attribute"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="separator" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:string"/>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="details">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="detailslevel" type="detailslevel" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="detailslevel">
		<xs:sequence>
			<xs:element name="label" type="xs:string"/>
			<xs:choice>
				<xs:element name="path">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="attribute" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="detailslevel" type="detailslevel" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Wirecloud/ogc-nomenclator-geowidget/js/service-config/Cartociudad-WFS-Distrito-Censal.xml
<?xml version="1.0" encoding="UTF-8"?>

<serviceConfig
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='./js/conwet/service-config/service_config.xsd'>
    <request>
        <url>http://www.cartociudad.es/wfs-distrito/services</url>
        <namespace>xmlns(app=http://www.deegree.org/app)</namespace>
        <version>1.1.0</version>
        <typename>app:Entidad</typename>
        <filter><![CDATA[<Filter xmlns:app="http://www.deegree.org/app"><PropertyIsLike matchCase="false" wildCard="*" singleChar="?" escapeChar="!"><PropertyName>{{prop_muni}}</PropertyName><Literal>*{{muni}}*</Literal></PropertyIsLike></Filter>]]></filter>
        <search>
            <option id="muni" label="Municipio">entidadLocal/municipio</option>
        </search>
    </request>
    <results>
        <locationInfo>nombreEntidad/nombre</locationInfo>
        <location>posicionEspacial/Point/pos</location>
        <srs attribute="srsName">posicionEspacial/boundedBy/Envelope</srs>
        <outputText>nombreEntidad/nombre</outputText>
        <displayInfo>nombreEntidad/nombre</displayInfo>
        <displayInfo headChar="(" trailChar=")">tipoEntidad/tipo</displayInfo>
    </results>
    <details>
        <detailslevel>
            <label>Nombre de entidad</label>
            <detailslevel>
                <label>Nombre</label>
                <path>nombreEntidad/nombre</path>
            </detailslevel>
            <detailslevel>
                <label>Idioma</label>
                <path>nombreEntidad/idioma</path>
            </detailslevel>
            <detailslevel>
                <label>Clase</label>
                <path>nombreEntidad/claseNombre</path>
            </detailslevel>
            <detailslevel>
                <label>Estatus</label>
                <path>nombreEntidad/estatus</path>
            </detailslevel>
            <detailslevel>
                <label>Fuente</label>
                <path>nombreEntidad/fuente</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>Tipo de entidad</label>
            <detailslevel>
                <label>Tipo</label>
                <path>tipoEntidad/tipo</path>
            </detailslevel>
            <detailslevel>
                <label>CatalogoEntidades</label>
                <path>tipoEntidad/catalogoEntidades</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>Posicion Espacial</label>
            <detailslevel>
                <label>Posicion</label>
                <path>posicionEspacial/Point/pos</path>
            </detailslevel>
            <detailslevel>
                <label>SRS</label>
                <path attribute="srsName">posicionEspacial/boundedBy/Envelope</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>Entidad local</label>
            <detailslevel>
                <label>Provincia</label>
                <path>entidadLocal/provincia</path>
            </detailslevel>
            <detailslevel>
                <label>Municipio</label>
                <path>entidadLocal/municipio</path>
            </detailslevel>
        </detailslevel>
    </details>
</serviceConfig>

=== Wirecloud/ogc-nomenclator-geowidget/js/service-config/IDEE-WFS-Nomenclator-NGC.xml
<?xml version="1.0" encoding="UTF-8"?>

<serviceConfig
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='./js/conwet/service-config/service_config.xsd'>
    <request>
        <url>http://www.idee.es/IDEE-WFS-Nomenclator-NGC/services</url>
        <namespace>xmlns(mne=http://www.idee.es/mne)</namespace>
        <version>1.1.0</version>
        <typename>mne:Entidad</typename>
        <filter><![CDATA[<Filter xmlns:mne="http://www.idee.es/mne"><PropertyIsLike matchCase="false" wildCard="*" singleChar="?" escapeChar="!"><PropertyName>{{prop_name}}</PropertyName><Literal>*{{name}}*</Literal></PropertyIsLike></Filter>]]></filter>
        <search>
            <option id="name" label="Nombre">mne:nombreEntidad/mne:NombreEntidad/mne:nombre</option>
        </search>
    </request>
    <results>
        <locationInfo>nombreEntidad/NombreEntidad/nombre</locationInfo>
        <location>posicionEspacial/PosicionEspacial/geometria/Point/pos</location>
        <srs attribute="srsName">posicionEspacial/PosicionEspacial/geometria/Point</srs>
        <outputText>nombreEntidad/NombreEntidad/nombre</outputText>
        <displayInfo>nombreEntidad/NombreEntidad/nombre</displayInfo>
        <displayInfo headChar="(" trailChar=")">tipoEntidad/TipoEntidad/tipo</displayInfo>
    </results>
    <details>
        <detailslevel>
            <label>NombreEntidad</label>
            <detailslevel>
                <label>Nombre</label>
                <path>nombreEntidad/NombreEntidad/nombre</path>
            </detailslevel>
            <detailslevel>
                <label>Idioma</label>
                <path>nombreEntidad/NombreEntidad/idioma</path>
            </detailslevel>
            <detailslevel>
                <label>ClaseNombre</label>
                <path>nombreEntidad/NombreEntidad/claseNombre</path>
            </detailslevel>
            <detailslevel>
                <label>Estatus</label>
                <path>nombreEntidad/NombreEntidad/estatus</path>
            </detailslevel>
            <detailslevel>
                <label>Fuente</label>
                <path>nombreEntidad/NombreEntidad/fuente</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>TipoEntidad</label>
            <detailslevel>
                <label>Tipo</label>
                <path>tipoEntidad/TipoEntidad/tipo</path>
            </detailslevel>
            <detailslevel>
                <label>CatalogoEntidades</label>
                <path>tipoEntidad/TipoEntidad/catalogoEntidades</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>PosicionEspacial</label>
            <detailslevel>
                <label>Posicion</label>
                <path>posicionEspacial/PosicionEspacial/geometria/Point/pos</path>
            </detailslevel>
            <detailslevel>
                <label>SRS</label>
                <path attribute="srsName">posicionEspacial/PosicionEspacial/geometria/Point</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>EntidadLocal</label>
            <detailslevel>
                <label>ComunidadAutonoma</label>
                <path>entidadLocal/EntidadLocal/comunidadAutonoma</path>
            </detailslevel>
            <detailslevel>
                <label>Provincia</label>
                <path>entidadLocal/EntidadLocal/provincia</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>Codificacion</label>
            <detailslevel>
                <label>Codigo</label>
                <path>codificacion/Codificacion/codigo</path>
            </detailslevel>
            <detailslevel>
                <label>SistemaCodificacion</label>
                <path>codificacion/Codificacion/sistemaCodificacion</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>Mapa</label>
            <detailslevel>
                <label>Serie</label>
                <path>mapa/Mapa/serie</path>
            </detailslevel>
            <detailslevel>
                <label>Hoja</label>
                <path>mapa/Mapa/hoja</path>
            </detailslevel>
        </detailslevel>
    </details>
</serviceConfig>

=== Wirecloud/ogc-nomenclator-geowidget/js/service-config/Cartociudad-WFS-Portal.xml
<?xml version="1.0" encoding="UTF-8"?>

<serviceConfig
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='./js/conwet/service-config/service_config.xsd'>
    <request>
        <url>http://www.cartociudad.es/wfs-portal/services</url>
        <namespace>xmlns(app=http://www.deegree.org/app)</namespace>
        <version>1.1.0</version>
        <typename>app:Entidad</typename>
        <filter><![CDATA[<Filter xmlns:app="http://www.deegree.org/app"><PropertyIsLike matchCase="false" wildCard="*" singleChar="?" escapeChar="!"><PropertyName>{{prop_name}}</PropertyName><Literal>*{{name}}*</Literal></PropertyIsLike></Filter>]]></filter>
        <search>
            <option id="name" label="Nombre">nombreEntidad/nombre</option>
        </search>
    </request>
    <results>
        <locationInfo>nombreEntidad/nombre</locationInfo>
        <location>posicionEspacial/Point/pos</location>
        <srs attribute="srsName">posicionEspacial/boundedBy/Envelope</srs>
        <outputText>nombreEntidad/nombre</outputText>
        <displayInfo>nombreEntidad/nombre</displayInfo>
        <displayInfo headChar="(" trailChar=")">tipoEntidad/tipo</displayInfo>
    </results>
    <details>
        <detailslevel>
            <label>Nombre de entidad</label>
            <detailslevel>
                <label>Nombre</label>
                <path>nombreEntidad/nombre</path>
            </detailslevel>
            <detailslevel>
                <label>Idioma</label>
                <path>nombreEntidad/idioma</path>
            </detailslevel>
            <detailslevel>
                <label>Clase</label>
                <path>nombreEntidad/claseNombre</path>
            </detailslevel>
            <detailslevel>
                <label>Estatus</label>
                <path>nombreEntidad/estatus</path>
            </detailslevel>
            <detailslevel>
                <label>Fuente</label>
                <path>nombreEntidad/fuente</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>Tipo de entidad</label>
            <detailslevel>
                <label>Tipo</label>
                <path>tipoEntidad/tipo</path>
            </detailslevel>
            <detailslevel>
                <label>CatalogoEntidades</label>
                <path>tipoEntidad/catalogoEntidades</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>Posicion Espacial</label>
            <detailslevel>
                <label>Posicion</label>
                <path>posicionEspacial/boudedBy/Envelope/pos</path>
            </detailslevel>
            <detailslevel>
                <label>SRS</label>
                <path attribute="srsName">posicionEspacial/Point</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>Entidad relacionada</label>
            <detailslevel>
                <label>Id entidad</label>
                <path>entidadRelacionada/idEntidad</path>
            </detailslevel>
            <detailslevel>
                <label>Descripción de relación</label>
                <path>entidadRelacionada/descripcionRelacion</path>
            </detailslevel>
            <detailslevel>
                <label>Tipo de relación</label>
                <path>entidadRelacionada/tipoRelacion</path>
            </detailslevel>
        </detailslevel>
        <detailslevel>
            <label>Entidad local</label>
            <detailslevel>
                <label>Provincia</label>
                <path>entidadLocal/provincia</path>
            </detailslevel>
            <detailslevel>
                <label>Municipio</label>
                <path>entidadLocal/municipio</path>
            </detailslevel>
        </detailslevel>
    </details>
</serviceConfig>
